# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd).$(BuildCounter)

parameters:
- name: SkipDependencyCheck
  displayName: "Skip dependency check"
  type: boolean
  default: true

trigger:
- main
- release/*

pool: NautilusBuild

variables:
- name: BuildConfiguration
  value: "release"
- name: BuildPlatform
  value: "any cpu"
- name: BuildCounter
  value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
- name: UKHOAssemblyCompany
  value: "UK Hydrographic Office"
- name: UKHOAssemblyVersionPrefix
  value: "2.0."
- name: UKHOAssemblyProduct
  value: "File Share Dotnet Client"
- name: SdkVersion
  value: "8.0.x"
- name: BuildTaskFramework
  value: "net8.0"

stages:
- stage: PERFORM_DEPENDENCYCHECK_DOTNETBUILD_DOTNETTEST_AND_PUBLISH
  displayName: Build, test and publish
  dependsOn: []
  jobs:
  - job: BuildTestPublish
    workspace:
      clean: all
    displayName: Build, unit test and package
    variables:
    - group: Client Library Integration Tests
    steps:
    - task: PowerShell@2
      displayName: "Output Environment Variables"
      inputs:
        targetType: inline
        script: |
          gci env:
          $CurrentYear = Get-Date -Format "yyyy"
          $AssemblyCopyright = "Copyright © UK Hydrographic  Office $CurrentYear"
          echo "##vso[task.setvariable variable=UKHOAssemblyCopyright]${AssemblyCopyright}"

    - task: PowerShell@2
      displayName: Set assembly version numbers based on build ID
      name: SetAssemblyVersion
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)\Apply-AssemblyVersionAndDefaults.ps1'
        arguments: >
          -buildNumber "$(Build.BuildNumber)"
          -solutionDirectory "$(Build.SourcesDirectory)\"
          -UKHOAssemblyCompany "$env:UKHOAssemblyCompany"
          -UKHOAssemblyCopyright "$env:UKHOAssemblyCopyright"
          -UKHOAssemblyVersionPrefix "$env:UKHOAssemblyVersionPrefix"
          -UKHOAssemblyProduct "$env:UKHOAssemblyProduct"
          -SourceRevisionId "$(Build.SourceVersion)"
          
    - task: UseDotNet@2
      displayName: 'Use .NET $(SdkVersion) sdk'
      inputs:
        packageType: sdk
        version: $(SdkVersion)

    - task: DotNetCoreCLI@2
      displayName: .Net Core - NuGet restore non-test projects
      inputs:
        command: restore
        projects: |
          **/*.csproj
          !**/*Tests*.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        workingDirectory: '$(Build.SourcesDirectory)'
        packagesDirectory: '$(Build.SourcesDirectory)\packages'

    - task: CmdLine@1
      condition: ne('${{ parameters.SkipDependencyCheck }}', true)
      displayName: Run OWASP Dependency Checker
      inputs:
        filename: 'dependency-check.bat'
        arguments: '--project "File-Share-Service-.Net-Client - $(Build.SourceBranchName)" --scan "$(Build.SourcesDirectory)" --out "$(Build.SourcesDirectory)\DCReport" --suppression $(Build.SourcesDirectory)\NVDSuppressions.xml --noupdate'

    - task: PublishBuildArtifacts@1
      condition: ne('${{ parameters.SkipDependencyCheck }}', true)
      displayName: "Publish Artifact: OWASP Dependency Checker Report"
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\DCReport'
        ArtifactName: "OWASP Dependency Checker Report"

    - task: PowerShell@1
      condition: ne('${{ parameters.SkipDependencyCheck }}', true)
      displayName: Fail Build if Dependency Check Finds Any Vulnerabilities
      inputs:
        scriptType: inlineScript
        arguments: '-ReportLocation $(Build.SourcesDirectory)\DCReport\*'
        inlineScript: |
          param($ReportLocation)
          Invoke-VulnerabilityCheck -ReportLocation $ReportLocation

    - task: DotNetCoreCLI@2
      displayName: .Net Core - NuGet restore for test projects
      inputs:
        command: restore
        projects: |
          **/*Tests*.csproj
          !**/FileShareClientIntegrationTests.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        workingDirectory: '$(Build.SourcesDirectory)'
        packagesDirectory: '$(Build.SourcesDirectory)\packagesForTests'
    
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: |
          **/*.csproj
          !**/FileShareClientIntegrationTests.csproj
        arguments: '--framework $(BuildTaskFramework) --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        projects: |
          **/*Tests.csproj
          !**/FileShareClientIntegrationTests.csproj
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'
        testRunTitle: UnitTests
          
    - task: DotNetCoreCLI@2
      displayName: Pack Project
      inputs:
        command: pack
        projects: |
          **/FileShareClient.csproj
          **/FileShareAdminClient.csproj
          !**/*Tests*.csproj
        packDirectory: $(Build.ArtifactStagingDirectory)/packages
        arguments:  '--configuration $(BuildConfiguration)'

    - task: PowerShell@2
      displayName: Include new packages in integration tests
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)\AddProjectReferences.ps1'
        arguments: >
          -SourcesDirectory "$(Build.SourcesDirectory)"
          -NuGetVersion "$(SetAssemblyVersion.NuGetVersion)"
          -PackagePath "$(Build.ArtifactStagingDirectory)\packages"

    - task: DotNetCoreCLI@2
      displayName: Integration tests - NuGet restore
      inputs:
        command: restore
        projects: |
          **/FileShareClientIntegrationTests.csproj
        feedsToUse: config
        noCache: true
        nugetConfigPath: '$(Build.SourcesDirectory)\BuildNuget.config'
        restoreDirectory: '$(Build.SourcesDirectory)\packagesForTests'

    - task: DotNetCoreCLI@2
      displayName: Integration tests - dotnet build
      inputs:
        command: build
        projects: |
          **/FileShareClientIntegrationTests.csproj
        arguments: '--framework $(BuildTaskFramework) --configuration $(BuildConfiguration) --output $(Build.BinariesDirectory)\integrationtests --no-restore'

    - task: PublishPipelineArtifact@1
      displayName: Publish integration tests artifact
      inputs:
        path: $(Build.BinariesDirectory)\integrationtests
        artifact: IntegrationTests

    # - task: FileTransform@2
    #   displayName: Integration tests - file transform
    #   inputs:
    #     folderPath: $(Build.BinariesDirectory)\integrationtests
    #     xmlTransformationRules:
    #     jsonTargetFiles: 'appsettings.json'

    # - task: PublishPipelineArtifact@1
    #   displayName: REMOVE - Publish settings
    #   inputs:
    #     path: $(Build.BinariesDirectory)\integrationtests\appsettings.json
    #     artifact: Settings

    # - task: DotNetCoreCLI@2
    #   displayName: Integration tests - dotnet test
    #   inputs:
    #     command: test
    #     projects: |
    #       $(Build.BinariesDirectory)\integrationtests\FileShareClientIntegrationTests.dll
    #     testRunTitle: IntegrationTests

    # - task: PublishPipelineArtifact@1
    #   displayName: REMOVE - Publish source
    #   inputs:
    #     path: $(Build.SourcesDirectory)
    #     artifact: Sources

    # - task: PublishPipelineArtifact@1
    #   displayName: REMOVE - Publish integration tests build
    #   inputs:
    #     path: $(Build.BinariesDirectory)\integrationtests
    #     artifact: Integration test build

    # - task: PublishPipelineArtifact@1
    #   displayName: Publish Pipeline Artifact
    #   inputs:
    #     path: $(Build.ArtifactStagingDirectory)
    #     artifact: $(Build.DefinitionName)
          
    - task: PublishPipelineArtifact@1
      displayName: Publish NuGet Package Artifacts
      inputs:
        path: $(Build.ArtifactStagingDirectory)/packages
        artifact: NuGetPackages

  - job:
    dependsOn: BuildTestPublish
    displayName: Integration tests
    variables:
    - group: Client Library Integration Tests
    steps:
    - download: current
      displayName: Download integration tests
      artifact: IntegrationTests

    - task: FileTransform@2
      displayName: File transform
      inputs:
        folderPath: $(Pipeline.Workspace)\IntegrationTests
        xmlTransformationRules:
        jsonTargetFiles: 'appsettings.json'

    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: test
        projects: |
          $(Pipeline.Workspace)\IntegrationTests\FileShareClientIntegrationTests.dll
        testRunTitle: IntegrationTests

- stage: Proget
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - group: nuget-deployment-vars
  jobs:
  - deployment: Publish_To_ProGetCloud
    displayName: Publish To ProGetCloud
    pool:
      name: NautilusRelease
    environment: FileShareDotNetClient-ProGet
    strategy:
      runOnce:
        deploy:
          steps:              
          - task: UseDotNet@2
            displayName: 'Use .NET $(SdkVersion) sdk'
            inputs:
              packageType: sdk
              version: $(SdkVersion)

          - download: current
            artifact: NuGetPackages

          - powershell: Get-ChildItem "$(Pipeline.Workspace)/NuGetPackages/*.nupkg" -File | Foreach {dotnet nuget push $_.fullname -k $(progetApiKey) -s https://progetcloud.ukho.gov.uk/nuget/ukho.trusted/v3/index.json }
            env:
              progetApiKey : $(progetApiKey)
            displayName: Publish Package
            
- stage: Nuget
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
  - group: nuget-deployment-vars
  jobs:
  - deployment: Publish_To_NuGet
    displayName: Publish To NuGet
    pool: 
      name: NautilusRelease
    environment: FileShareDotNetClient-NuGet
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            displayName: 'Use .NET $(SdkVersion) sdk'
            inputs:
              packageType: sdk
              version: $(SdkVersion)

          - download: current
            artifact: NuGetPackages

          - powershell: Get-ChildItem "$(Pipeline.Workspace)/NuGetPackages/UKHO.FileShareClient.*.nupkg" -File | Foreach {dotnet nuget push $_.fullname -k $(nugetApiKey) -s https://api.nuget.org/v3/index.json --no-symbols true}
            env:
              nugetApiKey : $(nugetApiKey)
            displayName: Publish Package
